# Generated by Django 3.0.3 on 2020-02-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedstudentsregDayscholars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(db_column='RegNo', max_length=11)),
            ],
            options={
                'db_table': 'allowedstudentsreg_dayscholars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=2)),
                ('lab_batch', models.IntegerField()),
                ('date', models.DateField()),
                ('no_hours', models.DecimalField(decimal_places=2, max_digits=11)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'db_table': 'attendance_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('count', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('rollno', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'attendance_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutoReg',
            fields=[
                ('regno', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, max_length=7, null=True)),
                ('course_list', models.CharField(blank=True, max_length=62, null=True)),
            ],
            options={
                'db_table': 'auto_reg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=25)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'block_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_id', models.IntegerField(blank=True, null=True)),
                ('reg_structure_id', models.IntegerField(blank=True, null=True)),
                ('reg_session_id', models.IntegerField(blank=True, null=True)),
                ('reg_session_name', models.CharField(blank=True, max_length=128, null=True)),
                ('reg_department_id', models.IntegerField(blank=True, null=True)),
                ('reg_department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_specialization_id', models.IntegerField(blank=True, null=True)),
                ('reg_specialization_name', models.CharField(blank=True, max_length=256, null=True)),
                ('reg_semester', models.IntegerField(blank=True, null=True)),
                ('reg_section', models.CharField(blank=True, max_length=2, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('structure_id', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=2, null=True)),
                ('course_id', models.CharField(blank=True, max_length=9, null=True)),
                ('course_name', models.CharField(blank=True, max_length=67, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('course_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('backlog', models.IntegerField(blank=True, null=True)),
                ('registered_on', models.DateTimeField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField()),
                ('pre_registered', models.IntegerField(blank=True, null=True)),
                ('approved', models.IntegerField(blank=True, null=True)),
                ('academic_fee_status', models.IntegerField(blank=True, null=True)),
                ('hostel_fee_status', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'comp_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseAllottedMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'course_allotted_mode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseFacultyAllotted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_course_id', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('batch_index', models.IntegerField()),
                ('faculty_id', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'course_faculty_allotted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=67)),
                ('credit', models.IntegerField()),
                ('type', models.IntegerField()),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoursesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'courses_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('specialization_id', models.IntegerField()),
            ],
            options={
                'db_table': 'department_specialization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailedDepartmentSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization_id', models.IntegerField()),
                ('specialization_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'detailed_department_specialization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailedDumRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_id', models.IntegerField(blank=True, null=True)),
                ('reg_structure_id', models.IntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('reg_section', models.CharField(blank=True, max_length=2, null=True)),
                ('pre_registered', models.IntegerField(blank=True, null=True)),
                ('approved', models.IntegerField(blank=True, null=True)),
                ('academic_fee_status', models.IntegerField(blank=True, null=True)),
                ('hostel_fee_status', models.IntegerField(blank=True, null=True)),
                ('reg_session_id', models.IntegerField(blank=True, null=True)),
                ('reg_session_name', models.CharField(blank=True, max_length=128, null=True)),
                ('reg_department_id', models.IntegerField(blank=True, null=True)),
                ('reg_department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_specialization_id', models.IntegerField(blank=True, null=True)),
                ('reg_specialization_name', models.CharField(blank=True, max_length=256, null=True)),
                ('reg_semester', models.IntegerField(blank=True, null=True)),
                ('course_id', models.CharField(max_length=9)),
                ('batch', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('registered_on', models.DateTimeField()),
                ('last_modified_on', models.DateTimeField()),
                ('backlog', models.IntegerField()),
                ('course_name', models.CharField(blank=True, max_length=67, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('course_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'detailed_dum_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailedRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_id', models.IntegerField(blank=True, null=True)),
                ('reg_structure_id', models.IntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('reg_section', models.CharField(max_length=2)),
                ('pre_registered', models.IntegerField(blank=True, null=True)),
                ('approved', models.IntegerField(blank=True, null=True)),
                ('academic_fee_status', models.IntegerField(blank=True, null=True)),
                ('hostel_fee_status', models.IntegerField(blank=True, null=True)),
                ('reg_session_id', models.IntegerField(blank=True, null=True)),
                ('reg_session_name', models.CharField(blank=True, max_length=128, null=True)),
                ('reg_department_id', models.IntegerField(blank=True, null=True)),
                ('reg_department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_specialization_id', models.IntegerField(blank=True, null=True)),
                ('reg_specialization_name', models.CharField(blank=True, max_length=256, null=True)),
                ('reg_semester', models.IntegerField(blank=True, null=True)),
                ('course_id', models.CharField(max_length=9)),
                ('batch', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('registered_on', models.DateTimeField()),
                ('last_modified_on', models.DateTimeField()),
                ('backlog', models.IntegerField()),
                ('course_name', models.CharField(blank=True, max_length=67, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('course_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'detailed_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailedStructure',
            fields=[
                ('structure_id', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty_id', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField()),
                ('department_id', models.IntegerField()),
                ('department_name', models.CharField(max_length=100)),
                ('specialization_id', models.IntegerField()),
                ('specialization_name', models.CharField(max_length=256)),
                ('session_id', models.IntegerField()),
                ('session_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'detailed_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamOnly',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('regno2', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'exam_only',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeesPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=100, unique=True)),
                ('hostel_fees_status', models.IntegerField()),
                ('amount_to_be_paid', models.IntegerField()),
                ('student_paid', models.IntegerField()),
                ('faculty_advisor_approved', models.IntegerField()),
            ],
            options={
                'db_table': 'fees_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewRollList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('roll_no', models.IntegerField()),
                ('reg_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'new_roll_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10)),
                ('pre_registered', models.IntegerField()),
                ('approved', models.IntegerField()),
                ('academic_fee_status', models.IntegerField()),
                ('hostel_fee_status', models.IntegerField()),
            ],
            options={
                'db_table': 'registered',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('backlog', models.IntegerField()),
                ('registered_on', models.DateTimeField()),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'registered_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredCoursesOld',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('registered_id', models.IntegerField()),
                ('structure_id', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('course_id', models.CharField(max_length=9)),
                ('batch', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('backlog', models.IntegerField()),
                ('registered_on', models.DateTimeField()),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'registered_courses_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredCoursesOops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_id', models.IntegerField()),
                ('structure_id', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('course_id', models.CharField(max_length=9)),
                ('batch', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('backlog', models.IntegerField()),
                ('registered_on', models.DateTimeField()),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'registered_courses_oops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'registered_mode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredOld',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=10)),
                ('reg_structure_id', models.IntegerField()),
                ('reg_section', models.CharField(max_length=2)),
                ('pre_registered', models.IntegerField()),
                ('approved', models.IntegerField()),
                ('academic_fee_status', models.IntegerField()),
                ('hostel_fee_status', models.IntegerField()),
            ],
            options={
                'db_table': 'registered_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationAllottedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_course_id', models.IntegerField()),
                ('structure_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=9)),
                ('course_mode', models.IntegerField()),
                ('course_type', models.IntegerField(blank=True, null=True)),
                ('course_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_mode_name', models.CharField(blank=True, max_length=50, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('course_name', models.CharField(blank=True, max_length=67, null=True)),
                ('section', models.CharField(blank=True, max_length=2, null=True)),
                ('batch_index', models.IntegerField(blank=True, null=True)),
                ('faculty_id', models.IntegerField(blank=True, null=True)),
                ('cfid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registration_allotted_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegularCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=9)),
                ('course_mode', models.IntegerField()),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'regular_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10)),
                ('reg_structure_id', models.IntegerField()),
                ('reg_section', models.CharField(max_length=2)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'requested',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_id', models.IntegerField()),
                ('structure_id', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('course_id', models.CharField(max_length=9)),
                ('batch', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('backlog', models.IntegerField()),
                ('dropped', models.IntegerField()),
                ('registered_on', models.DateTimeField()),
                ('last_modified_on', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'requested_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_modified_on', models.DateTimeField()),
                ('results_publish', models.IntegerField()),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=256)),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'specialization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
                ('specialization_id', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StructureOverride',
            fields=[
                ('regno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('structure_id', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=5)),
                ('session_id', models.IntegerField()),
            ],
            options={
                'db_table': 'structure_override',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StructureSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'structure_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudCurrRegStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10)),
                ('specialization', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=2)),
                ('current_year', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stud_curr_reg_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('roll_number', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('current_section', models.CharField(blank=True, max_length=40, null=True)),
                ('current_year', models.CharField(max_length=4)),
                ('joining_year', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=16)),
                ('emergency_contact', models.CharField(max_length=16)),
                ('sbh_account', models.CharField(blank=True, max_length=32, null=True)),
                ('passport', models.CharField(blank=True, max_length=20, null=True)),
                ('hostel_room', models.CharField(max_length=10)),
                ('hostel', models.CharField(max_length=10)),
                ('mess', models.CharField(max_length=10)),
                ('created_location', models.CharField(max_length=32)),
                ('created_time', models.DateTimeField()),
                ('guardian1', models.CharField(blank=True, max_length=64, null=True)),
                ('relationship1', models.CharField(blank=True, max_length=64, null=True)),
                ('email1', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile1', models.CharField(blank=True, max_length=16, null=True)),
                ('guardian2', models.CharField(blank=True, max_length=64, null=True)),
                ('relationship2', models.CharField(blank=True, max_length=64, null=True)),
                ('email2', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=16, null=True)),
                ('homenumber', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=50, null=True)),
                ('adhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('mac', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'student_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_1', models.CharField(blank=True, db_column='COL 1', max_length=37, null=True)),
                ('col_2', models.CharField(blank=True, db_column='COL 2', max_length=7, null=True)),
                ('col_3', models.CharField(blank=True, db_column='COL 3', max_length=7, null=True)),
                ('col_4', models.CharField(blank=True, db_column='COL 4', max_length=39, null=True)),
                ('col_5', models.CharField(blank=True, db_column='COL 5', max_length=14, null=True)),
                ('col_6', models.CharField(blank=True, db_column='COL 6', max_length=8, null=True)),
                ('cid', models.CharField(blank=True, max_length=6, null=True)),
                ('cname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'timestamp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimestampRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'timestamp_requested',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimestampSession10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'timestamp_session_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimestampSession9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'timestamp_session_9',
                'managed': False,
            },
        ),
    ]
