# Generated by Django 3.0.3 on 2020-02-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_code', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=28, null=True)),
                ('department', models.CharField(blank=True, max_length=40, null=True)),
                ('designation', models.CharField(blank=True, max_length=20, null=True)),
                ('facid', models.CharField(blank=True, max_length=5, null=True)),
                ('specialization', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'factemp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyCurrentData',
            fields=[
                ('facultyid', models.AutoField(primary_key=True, serialize=False)),
                ('drupal_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=20)),
                ('interest', models.TextField(blank=True, null=True)),
                ('department', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=5000, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('office', models.CharField(blank=True, max_length=20, null=True)),
                ('officeaddress', models.CharField(blank=True, max_length=5000, null=True)),
                ('extlinks', models.CharField(blank=True, max_length=5000, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('edit', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('approve_ipaddress', models.CharField(max_length=50)),
                ('approve_by', models.CharField(max_length=50)),
                ('courses', models.TextField(blank=True, null=True)),
                ('phds', models.TextField(blank=True, null=True)),
                ('workshops', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('publications', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faculty_current_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyCurrentData33',
            fields=[
                ('facultyid', models.AutoField(primary_key=True, serialize=False)),
                ('drupal_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=20)),
                ('interest', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=5000, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('office', models.CharField(max_length=20)),
                ('officeaddress', models.CharField(max_length=5000)),
                ('extlinks', models.CharField(max_length=5000)),
                ('profile', models.TextField(blank=True, null=True)),
                ('edit', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('approve_ipaddress', models.CharField(max_length=50)),
                ('approve_by', models.CharField(max_length=50)),
                ('courses', models.TextField(blank=True, null=True)),
                ('phds', models.TextField(blank=True, null=True)),
                ('workshops', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('publications', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faculty_current_data33',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_code', models.IntegerField()),
                ('designation_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'faculty_designation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation_name', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=5000, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('office', models.CharField(blank=True, max_length=20, null=True)),
                ('officeaddress', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'faculty_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyPendingData',
            fields=[
                ('facultyid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('interest', models.TextField()),
                ('phone', models.CharField(max_length=256)),
                ('office', models.CharField(max_length=100)),
                ('officeaddress', models.CharField(max_length=5000)),
                ('extlinks', models.CharField(max_length=5000)),
                ('email', models.CharField(max_length=100)),
                ('profile', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('review', models.IntegerField(blank=True, null=True)),
                ('saved', models.IntegerField()),
                ('ipaddress', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('courses', models.TextField(blank=True, null=True)),
                ('phds', models.TextField(blank=True, null=True)),
                ('workshops', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('publications', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faculty_pending_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=16)),
                ('login', models.CharField(max_length=100)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_attempts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=80)),
                ('salt', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(max_length=100)),
                ('activation_code', models.CharField(blank=True, max_length=40, null=True)),
                ('forgotten_password_code', models.CharField(blank=True, max_length=40, null=True)),
                ('forgotten_password_time', models.PositiveIntegerField(blank=True, null=True)),
                ('remember_code', models.CharField(blank=True, max_length=40, null=True)),
                ('created_on', models.PositiveIntegerField()),
                ('last_login', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.PositiveIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('department_code', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'users_groups',
                'managed': False,
            },
        ),
    ]
