# Generated by Django 2.1.2 on 2020-02-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cgupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(blank=True, null=True, unique=True)),
                ('cgpa', models.DecimalField(blank=True, db_column='Cgpa', decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'cgupdate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=6)),
                ('department', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=67, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField()),
                ('last_edited_by', models.CharField(max_length=100)),
                ('last_modified_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElectiveForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.IntegerField()),
                ('class_code', models.IntegerField()),
                ('department_code', models.IntegerField(blank=True, null=True)),
                ('course_code', models.CharField(max_length=15)),
                ('course_name', models.CharField(blank=True, max_length=67, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField()),
                ('no_of_seats', models.IntegerField()),
                ('allotted_seats', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'elective_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EligibleStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=10, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eligible_students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentElectiveChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=16)),
                ('priority', models.IntegerField()),
            ],
            options={
                'db_table': 'student_elective_choices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentElectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=11, unique=True)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allotted', models.IntegerField()),
                ('allotted_elective', models.CharField(blank=True, max_length=10, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('ipaddress', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'student_electives',
                'managed': False,
            },
        ),
    ]
